"""added number_of_semester

Revision ID: 3267c94a040e
Revises: 897cb08ab000
Create Date: 2025-08-01 10:37:29.385237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3267c94a040e'
down_revision: Union[str, Sequence[str], None] = '897cb08ab000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('number_of_semester', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_number_of_semester'), 'posts', ['number_of_semester'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_number_of_semester'), table_name='posts')
    op.drop_column('posts', 'number_of_semester')
    # ### end Alembic commands ###
