"""added themes and tags arrays

Revision ID: 832df7f38452
Revises: ae9f328ef82c
Create Date: 2025-08-01 09:47:22.330072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '832df7f38452'
down_revision: Union[str, Sequence[str], None] = 'ae9f328ef82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('posts', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_index(op.f('ix_posts_image_url'), table_name='posts')
    op.create_index(op.f('ix_posts_tags'), 'posts', ['tags'], unique=False)
    op.create_index(op.f('ix_posts_themes'), 'posts', ['themes'], unique=False)
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_posts_themes'), table_name='posts')
    op.drop_index(op.f('ix_posts_tags'), table_name='posts')
    op.create_index(op.f('ix_posts_image_url'), 'posts', ['image_url'], unique=False)
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'themes')
    # ### end Alembic commands ###
