"""added course_description

Revision ID: 897cb08ab000
Revises: c4e546ff34ea
Create Date: 2025-08-01 10:24:04.744711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897cb08ab000'
down_revision: Union[str, Sequence[str], None] = 'c4e546ff34ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('course_description', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_course_description'), 'posts', ['course_description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_course_description'), table_name='posts')
    op.drop_column('posts', 'course_description')
    # ### end Alembic commands ###
