"""initial

Revision ID: ae9f328ef82c
Revises: 
Create Date: 2025-07-16 03:34:05.639143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9f328ef82c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.add_column('posts', sa.Column('course', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('course_summary', sa.String(), nullable=True))
    op.drop_index(op.f('ix_posts_description'), table_name='posts')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index(op.f('ix_posts_course'), 'posts', ['course'], unique=False)
    op.create_index(op.f('ix_posts_course_name'), 'posts', ['course_name'], unique=False)
    op.create_index(op.f('ix_posts_course_summary'), 'posts', ['course_summary'], unique=False)
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_posts_course_summary'), table_name='posts')
    op.drop_index(op.f('ix_posts_course_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_course'), table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_posts_description'), 'posts', ['description'], unique=False)
    op.drop_column('posts', 'course_summary')
    op.drop_column('posts', 'course_name')
    op.drop_column('posts', 'course')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
