"""added course_url

Revision ID: c4e546ff34ea
Revises: 832df7f38452
Create Date: 2025-08-01 09:57:03.013838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e546ff34ea'
down_revision: Union[str, Sequence[str], None] = '832df7f38452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('course_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_course_url'), 'posts', ['course_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_course_url'), table_name='posts')
    op.drop_column('posts', 'course_url')
    # ### end Alembic commands ###
